### Create
POST localhost:8080/article/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcyMjY2OTUsImlkIjoyLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNzA3MzEzMDk1LCJpc3MiOiJLdW5VelRlc3QifQ.asKVJjOZUKbl1ZauQlwVtLVo64z55AgfJUSb4k_CRgUYynQbjNdNBMN-BbbyuaDo6H59RYBDE9gIpcK79piu0g

{
  "title": "title1",
  "description": "d1",
  "articleType": [
    1,
    2
  ],
  "categoryId": 1,
  "photoId": "f6d5fa34-892b-4e80-b055-ed4a5dbce6b7",
  "regionId": 1,
  "content": "c1"
}


### Update
PUT localhost:8080/article/adm/dfdc452c-65f0-4316-90c9-9bb52b5f65af
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcyMjY2OTUsImlkIjoyLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNzA3MzEzMDk1LCJpc3MiOiJLdW5VelRlc3QifQ.asKVJjOZUKbl1ZauQlwVtLVo64z55AgfJUSb4k_CRgUYynQbjNdNBMN-BbbyuaDo6H59RYBDE9gIpcK79piu0g

{
  "articleType": [4,1]
}