### Like
POST localhost:8080/articleLike/like/59fbafed-86f0-4c20-88cb-0c47dd1bd94e
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwODU1NDAsImVtYWlsIjoic2hhbXNob2RvZGluYXlldjE3MDJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODE3MTk0MCwiaXNzIjoiS3VuVXpUZXN0In0.s3n7f46o6j5eKDhebNUAcOdSc5MeuMYMjZRjNyrHG6wA1j2k8JORZ_nggsWd5pPmDZWaAy82Wx6PSOEitt8BKA

### Dislike
POST localhost:8080/articleLike/dislike/59fbafed-86f0-4c20-88cb-0c47dd1bd94e
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc3MzEwMjEsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDc4MTc0MjEsImlzcyI6Ikt1blV6VGVzdCJ9.TopDEoa2WwC4MvVwRXHPj2vbYhshpNvwHCDZxziTSKGtKqVAyCmwXYBtgVv3tcMpOPoh04PHqiseXlXNC-IEoQ

### Remove
POST localhost:8080/articleLike/remove/59fbafed-86f0-4c20-88cb-0c47dd1bd94e
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc3MzEwMjEsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDc4MTc0MjEsImlzcyI6Ikt1blV6VGVzdCJ9.TopDEoa2WwC4MvVwRXHPj2vbYhshpNvwHCDZxziTSKGtKqVAyCmwXYBtgVv3tcMpOPoh04PHqiseXlXNC-IEoQ
