### Create
POST localhost:8080/article/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc3MzE2MjYsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDc4MTgwMjYsImlzcyI6Ikt1blV6VGVzdCJ9.5Gi_1WUrnvDgE5zHBY0k4-GLLlkK4JAPYTku6os7Y3Y75HBugZL8ZIk0mnF6KlHIDasXTVrTSC6UopQ9669U0w

{
  "title": "title1",
  "description": "d1",
  "articleType": [
    2,
    4
  ],
  "categoryId": 1,
  "photoId": "f6d5fa34-892b-4e80-b055-ed4a5dbce6b7",
  "regionId": 2,
  "content": "c1"
}


### Update
PUT localhost:8080/article/adm/dfdc452c-65f0-4316-90c9-9bb52b5f65af
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcyMjY2OTUsImlkIjoyLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNzA3MzEzMDk1LCJpc3MiOiJLdW5VelRlc3QifQ.asKVJjOZUKbl1ZauQlwVtLVo64z55AgfJUSb4k_CRgUYynQbjNdNBMN-BbbyuaDo6H59RYBDE9gIpcK79piu0g

{
  "articleType": [
    2,
    2
  ]
}

### Delete by id
DELETE localhost:8080/article/adm/dfdc452c-65f0-4316-90c9-9bb52b5f6qaf
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcyMjY2OTUsImlkIjoyLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNzA3MzEzMDk1LCJpc3MiOiJLdW5VelRlc3QifQ.asKVJjOZUKbl1ZauQlwVtLVo64z55AgfJUSb4k_CRgUYynQbjNdNBMN-BbbyuaDo6H59RYBDE9gIpcK79piu0g

### Change Status by id
PUT localhost:8080/article/adm/changeStatus/50a8dc5b-7c12-4625-acfe-c9dfed62f237
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDcyMjY2OTUsImlkIjoyLCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNzA3MzEzMDk1LCJpc3MiOiJLdW5VelRlc3QifQ.asKVJjOZUKbl1ZauQlwVtLVo64z55AgfJUSb4k_CRgUYynQbjNdNBMN-BbbyuaDo6H59RYBDE9gIpcK79piu0g

### Get by type and size
GET localhost:8080/article/getTypeId?typeId=1&size=2

### Not Listed
POST localhost:8080/article/notListed
Content-Type: application/json

{
  "articles": [
    "f6253f5b-6b6d-431d-b931-35f56ee1ba68"
  ],
  "size": 2
}

### Increase View Count
POST localhost:8080/article/increaseViewCount/d8cdf85d-c7b9-440b-b55a-35ba0cc2fac2

### Increase share view Count
POST localhost:8080/article/increaseShareViewCount/d8cdf85d-c7b9-440b-b55a-35ba0cc2fac2

### Get size most read articles
GET localhost:8080/article/getMostRead?size=2

### Get article type and region
GET localhost:8080/article/getTypeAndByRegion?typeId=2&regionId=2