### Upload file
POST http://localhost:8080/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="rasm3.jpg"

< C:\Users\Shamshod Odinayev\Desktop\rasm\rasm3.png

### GET
GET localhost:8080/attach/open/kunuz.jpg

### Get all
GET localhost:8080/attach/open_general/kunuz.jpg

### Dowlooad
GET localhost:8080/attach/download/c90305b8-0ab8-476c-a0a2-3718fef0a626


