### Login
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "admin@mail.ru",
  "password": "12345"
}

### Registration emailga xabar junatadi
POST localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "regis1ff",
  "surname": "regifs1",
  "email": "shamshod6696odinayev@gmail.com",
  "password": "aefafAWERrytWE3223FDg3w23"
}
