### Login
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}

### Registration
POST localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "regis1",
  "surname": "regis1",
  "email": "shamshododinayev1702@gmail.com",
  "password": "aefafAWERWE3223FDg3w23"
}