### Login
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "admin@mail.ru",
  "password": "12345"
}

### Registration
POST localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "regis1",
  "surname": "regis1",
  "email": "shamshododi1nayev1702@gmail.com",
  "password": "aefafAWERWE3223FDg3w23"
}