### Like
POST localhost:8080/commentLike/like/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwODU1NDAsImVtYWlsIjoic2hhbXNob2RvZGluYXlldjE3MDJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODE3MTk0MCwiaXNzIjoiS3VuVXpUZXN0In0.s3n7f46o6j5eKDhebNUAcOdSc5MeuMYMjZRjNyrHG6wA1j2k8JORZ_nggsWd5pPmDZWaAy82Wx6PSOEitt8BKA

### Dislike
POST localhost:8080/commentLike/dislike/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwODU1NDAsImVtYWlsIjoic2hhbXNob2RvZGluYXlldjE3MDJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODE3MTk0MCwiaXNzIjoiS3VuVXpUZXN0In0.s3n7f46o6j5eKDhebNUAcOdSc5MeuMYMjZRjNyrHG6wA1j2k8JORZ_nggsWd5pPmDZWaAy82Wx6PSOEitt8BKA

### Remove
POST localhost:8080/commentLike/remove/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwODU1NDAsImVtYWlsIjoic2hhbXNob2RvZGluYXlldjE3MDJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODE3MTk0MCwiaXNzIjoiS3VuVXpUZXN0In0.s3n7f46o6j5eKDhebNUAcOdSc5MeuMYMjZRjNyrHG6wA1j2k8JORZ_nggsWd5pPmDZWaAy82Wx6PSOEitt8BKA


