### Coomet create
POST localhost:8080/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5MTc4OTEsImVtYWlsIjoic2hhbXNob2RvZGluYXlldjE3MDJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODAwNDI5MSwiaXNzIjoiS3VuVXpUZXN0In0.oEK-ldR3yXn7ojLOe6fiB4mukfllo4hIycmlA0Yl2L99o_LsnQZiyYidf1g_cK7FDguyA1BNBGKHYyaPzyRQqA

{
  "content": "555",
  "articleId": "59fbafed-86f0-4c20-88cb-0c47dd1bd94e"
}

### Comment update
PUT localhost:8080/comment/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc5MTQ3NDYsImVtYWlsIjoic2hhbXNob2RvZGluYXlldjE3MDJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODAwMTE0NiwiaXNzIjoiS3VuVXpUZXN0In0.gvKoF5Aq67yPObPV45BJe7EHzL4Pc6ypT42ETCpID-XBYcY1kRiwocdiw1Sc_jKTZp0ZWI40OLbv353hmxCL5g

{
  "content": "Yaxshi"
}

### Delete comment
DELETE localhost:8080/comment/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwMDA5NjEsImVtYWlsIjoic2hhbXNob2RvZGluYXlldjE3MDJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODA4NzM2MSwiaXNzIjoiS3VuVXpUZXN0In0.YP6UyU_jP2zJpA54TxibMROWk1wQKJ_hmHe_8RPrnsSRIMvlE5gqXn1pqNWbXrLNeE5_k39zj1PPCmgpjWiMYg

### Get by articleId
GET localhost:8080/comment/59fbafed-86f0-4c20-88cb-0c47dd1bd94e
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwMDA5NjEsImVtYWlsIjoic2hhbXNob2RvZGluYXlldjE3MDJAZ21haWwuY29tIiwicm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcwODA4NzM2MSwiaXNzIjoiS3VuVXpUZXN0In0.YP6UyU_jP2zJpA54TxibMROWk1wQKJ_hmHe_8RPrnsSRIMvlE5gqXn1pqNWbXrLNeE5_k39zj1PPCmgpjWiMYg

### Pagination
GET localhost:8080/comment/pagination?page=1&size=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgyNzAxNDAsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MzU2NTQwLCJpc3MiOiJLdW5VelRlc3QifQ.qtedMLupm1tqOaugbXSa3L0Y6vUgcnRNWbsIBp7KeeJB_Jw91ZyYJ5pbGEEwPaap2Dw2suYuXXCo9P-EkPvycw


### Comment filter
POST localhost:8080/comment/filter?page=1&size=4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDgwMDYzMjAsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA4MDkyNzIwLCJpc3MiOiJLdW5VelRlc3QifQ._pJY9JcK_J6N8KvkTXwJujjfKxl0PusWliiRGMrkhIJxzPQRRS1UpwwFX-kAuHs_MieVrQ3Z3RpiH3IGS6W7Dw

{
  "articleId": "59fbafed-86f0-4c20-88cb-0c47dd1bd94e",
  "fromDate": "2024-02-14",
  "profileId": 12,
  "visible": true
}
