### Create profile
POST localhost:8080/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4NDA1NjQsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTI2OTY0LCJpc3MiOiJLdW5VelRlc3QifQ.JsjNZAYE7lA_9U-AENWXcKfROX8axPhca8ZPiSoR2mKJFXudEQQhYuxyLL-D0qTmLqZHGLM7Q19nMzSXYD2AYg

{
  "name": "Shamshod",
  "surName": "Odinayev",
  "password": "Shamshod123",
  "email": "shovv112d@gmail.com",
  "role": "ROLE_PUBLISHER",
  "status": "ACTIVE"
}

### Update profile
POST localhost:8080/profile/10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyNjAzNDMsImlkIjoxMSwicm9sZSI6IlVTRVIiLCJleHAiOjE3MDYzNDY3NDMsImlzcyI6Ikt1blV6VGVzdCJ9.gjQ3HdCIRXunKWMyC3n4sJF0QPTB7jw21MiPUSF6A4RANG2K1NboXYMBKB6vkkvIL2gdFKbxAhMZDtJ5o4vJoQ

{
  "role": "USER",
  "status": "BLOCK"
}

### Profile get all
GET localhost:8080/profile
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyODAzMzcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYzNjY3MzcsImlzcyI6Ikt1blV6VGVzdCJ9.qpE4c78kKM7muaQkLlqSfH6zajdkdFHyeqqCHytqUF8RoMjXjwah-oWhUpk9FgDU0uGIr71IujgOVWg8z-yspQ

### Profile Delete
DELETE localhost:8080/profile/7
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYxOTI4NDMsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYyNzkyNDMsImlzcyI6Ikt1blV6VGVzdCJ9.VfhFvv7UH8t8wTQt-xewB69uYGgdG_RgGCjleH9JvCNscLbGb4vfFyV5DkwMXnJ7ARRv5AC1KsRtFS0zVaWnfQ

### Profile filter
POST localhost:8080/profile/adm/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY0MzY5ODMsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1MjMzODMsImlzcyI6Ikt1blV6VGVzdCJ9.8ZppjXw7F5eA9SCdRHr2_5CJXJ98LeMFNnjs996gdKMSjkwp8vlhEwZ1wMHGWZTs15vxLPtvwSQhkNVZXmSH5g

{
  "name": "1",
  "surname": "1"
}