### Create region
POST localhost:8080/region
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDc4NDIxNTEsImVtYWlsIjoiYWRtaW5AbWFpbC5ydSIsInJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzA3OTI4NTUxLCJpc3MiOiJLdW5VelRlc3QifQ.Q_xP3pvtO8EvU1ARXKOv028j1PIrOc-qNrJjilYJV3HHreu7V2VJdJdzLNLq3KnYm_oNNm8Syo7FYjRKlm2Xbw

{
  "orderNumber": 5,
  "nameUz": "Qoraqalpog'iston",
  "nameEn": "Karakalpakstan",
  "nameRu": "Қорақалпоғистан"
}

### Update By id
POST localhost:8080/region/2
Content-Type: application/json

{
  "orderNumber": 3,
  "nameUz": "Andijon",
  "nameEn": "Andijan",
  "nameRu": "Андижан"
}

### Delete by id Region
DELETE localhost:8080/region/5

### Get all Region
GET localhost:8080/region

### Get by lang
GET localhost:8080/region/lang?lang=uz