### Create region
POST localhost:8080/region
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY5NzAyMjAsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDcwNTY2MjAsImlzcyI6Ikt1blV6VGVzdCJ9.fyUzgLmgRqvaao9bNzzW_eOeowvgrYseTNP5ZU3g5nMxQ1Qa_0HaPo7ZEFDxeN07Wjtt-Lf1X7tKMUlA6jEy9Q

{
  "orderNumber": 2,
  "nameUz": "Qoraqalpog'iston",
  "nameEn": "Karakalpakstan",
  "nameRu": "Қорақалпоғистан"
}

### Update By id
POST localhost:8080/region/2
Content-Type: application/json

{
  "orderNumber": 3,
  "nameUz": "Andijon",
  "nameEn": "Andijan",
  "nameRu": "Андижан"
}

### Delete by id Region
DELETE localhost:8080/region/5

### Get all Region
GET localhost:8080/region

### Get by lang
GET localhost:8080/region/lang?lang=uz